### ISSUE TITLE
Implement network state

### ISSUE THREAD

**Issue by stgraber** [lxc/incus-os#87]
/1.0/system/network should report network state.

Probably something like:
```
state:
  interfaces:
    enp1:
      addresses:
        - addr1
        - addr2
      routes:
        - to: 1.2.3.4/24
          via: 1.1.1.1
      speed: 10000
      state: up
      lldp:
        - name: neighbor1
          chassis_id: XYZ
          port_id: XYZ
          port: 1/2/3 (may be missing)
        - name: neighbor2
          chassis_id: XYZ
          port_id: XYZ
          port: 1/2/3 (may be missing)
      stats:
        rx_bytes: 123
        tx_bytes: 123
        rx_errors: 0
        tx_errors: 0
    enp2:
      addresses:
        - addr1
        - addr2
      routes:
        - to: 1.2.3.4/24
          via: 1.1.1.1
      speed: 10000
      state: up
      lldp:
        - name: neighbor1
          chassis_id: XYZ
          port_id: XYZ
          port: 1/2/3 (may be missing)
        - name: neighbor2
          chassis_id: XYZ
          port_id: XYZ
          port: 1/2/3 (may be missing)
      stats:
        rx_bytes: 123
        tx_bytes: 123
        rx_errors: 0
        tx_errors: 0
    my-bond:
      addresses:
        - addr1
        - addr2
      routes:
        - to: 1.2.3.4/24
          via: 1.1.1.1
      speed: 10000
      state: up
      members:
        enp3:
          state: up
          local_mac: MAC
          remote_mac: MAC
          stats:
            rx_bytes: 123
            tx_bytes: 123
            rx_errors: 0
            tx_errors: 0
          lldp:
            - name: neighbor1
              chassis_id: XYZ
              port_id: XYZ
              port: 1/2/3 (may be missing)
            - name: neighbor2
              chassis_id: XYZ
              port_id: XYZ
              port: 1/2/3 (may be missing)
        enp4:
          state: up
          local_mac: MAC
          remote_mac: MAC
          stats:
            rx_bytes: 123
            tx_bytes: 123
            rx_errors: 0
            tx_errors: 0   
          lldp:
            - name: neighbor1 (may be missing)
              chassis_id: XYZ
              port_id: XYZ
              port: 1/2/3 (may be missing)              
            - neighbor2
              chassis_id: XYZ
              port_id: XYZ
              port: 1/2/3 (may be missing)
      stats:
        rx_bytes: 123
        tx_bytes: 123
        rx_errors: 0
        tx_errors: 0   
```
